# Generated by Django 4.0.2 on 2022-02-23 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_tag_project_vote_ratio_project_vote_total_review_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='demo_link',
        ),
        migrations.RemoveField(
            model_name='project',
            name='source_link',
        ),
    ]
