# Generated by Django 4.0.3 on 2022-03-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_favourite_favourite_alter_favourite_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favourites',
            field=models.ManyToManyField(blank=True, default=None, related_name='favourite', to='users.profile'),
        ),
        migrations.DeleteModel(
            name='Favourite',
        ),
    ]
